### ISSUE TITLE
Branches listing

### ISSUE THREAD

**Issue by kimricher** [mshappe/ruby-the-gryphon#20]
Branches "index" page needs to be created

**Comment by mshappe** [comment]
Current thoughts:

* Tab name something like "Get Involved"
* Page lists branch and allows search by state. Maybe eventually by ZIP but only if we get the ZIPs in the DB associated with branches, which we don't currently have even tho' Cartographer/Seneschal has that data.
* Also search by name
* Like most of the tables, also sort by name, region, state?

That seems like a good start.

**Comment by mshappe** [comment]
Deployed to staging
