### ISSUE TITLE
Update error message when no address entered for Forgot Password

### ISSUE THREAD

**Issue by kimricher** [mshappe/ruby-the-gryphon#21]
"1 error prohibited this user from being saved:" should ideally have something more user-friendly OR be hidden to avoid confusion, because "email cannot be blank" does also show up as error message/description

**Comment by mshappe** [comment]
This messages comes out of the `devise` library, which at first glance sounds hard to fix; but the folks who write `devise` are Very Smart&trade;. All of the strings that matter are installed locally so they can be customized! So, this should be fixed shortly.
